import{useMemo,useState}from'react';
import{ArrowLeft,ArrowRight,CheckCircle2,FileCheck2,ReceiptText,ShieldCheck}from'lucide-react';
import{Entry,money,supabase}from'./lib';
import{printOfficialDailyRecord}from'./printDailyRecord';
import{AppLanguage,useLanguage}from'./useLanguage';

const today=new Date().toISOString().slice(0,10);
const initial={entry_date:today,opening_cash:'',sales_revenue:'',inventory_purchases:'',operating_expenses:'',other_money_in:'',other_money_out:'',closing_cash:'',notes:''};
const n=(value:unknown)=>Number(value)||0;

const copy={
  en:{title:'Daily entry',intro:'One simple question at a time. Your answers stay here until you submit.',locked:'Locked after submission',back:'Back',next:'Next',submit:'Submit daily record',saving:'Saving…',progress:'Step',of:'of',recent:'Recent records',print:'Print / PDF',salesShort:'Sales',cashShort:'Closing cash',balanced:'Balanced',difference:'Difference',success:'Daily record saved and protected.',duplicate:'A record already exists for this date. Ask the owner to correct it.',review:'Review today',reviewHelp:'Check the numbers before submitting. After submission, only the owner can correct the record.',expected:'Expected closing cash',actual:'Actual closing cash',cashDifference:'Cash difference',notes:'Notes',notesHelp:'Optional: explain shortages, unusual costs, damaged goods, or important events.',notesPlaceholder:'Short explanation, if needed.',questions:[
    ['Choose the date','Which business day are you recording? Usually this is today.'],
    ['Opening cash','Enter the cash counted when the store first opened today. Do not include inventory value.'],
    ['Sales / revenue','Enter all money earned from today’s sales, whether received as cash or recorded by your business.'],
    ['Inventory purchased','Enter the cost of goods bought for resale today—not the selling price.'],
    ['Operating expenses','Enter today’s wages, transport, loading, utilities, food, packaging, repairs and other running costs.'],
    ['Other money in','Enter non-sales cash received, including customer qarz repayment or other business money in.'],
    ['Other money out','Enter non-expense cash paid out, including qarz given, owner-approved withdrawal or other money out.'],
    ['Closing cash','Count the physical cash at the end of the day and enter the exact amount.'],
    ['Final check','Review the calculated cash difference and add a short note if it is not zero.']
  ]},
  fa:{title:'ثبت روزانه',intro:'هر بار فقط یک پرسش. پاسخ‌ها تا زمان ثبت محفوظ می‌مانند.',locked:'پس از ثبت قفل می‌شود',back:'قبلی',next:'بعدی',submit:'ثبت گزارش روزانه',saving:'در حال ثبت…',progress:'مرحله',of:'از',recent:'ثبت‌های اخیر',print:'چاپ',salesShort:'فروش',cashShort:'پول پایان',balanced:'برابر',difference:'تفاوت',success:'گزارش روزانه ثبت و محافظت شد.',duplicate:'برای این تاریخ قبلاً ثبت شده است. از مالک بخواهید اصلاح کند.',review:'بررسی امروز',reviewHelp:'پیش از ثبت ارقام را بررسی کنید. پس از ثبت فقط مالک می‌تواند اصلاح کند.',expected:'پول نقد مورد انتظار',actual:'پول نقد واقعی',cashDifference:'تفاوت پول نقد',notes:'یادداشت',notesHelp:'اختیاری: کمبود، مصرف غیرعادی، جنس خراب یا رویداد مهم را بنویسید.',notesPlaceholder:'در صورت نیاز توضیح کوتاه.',questions:[
    ['تاریخ','روز کاری مورد نظر را انتخاب کنید؛ معمولاً امروز.'],['پول آغاز روز','مبلغی را وارد کنید که هنگام باز کردن دکان شمردید. ارزش اجناس را شامل نکنید.'],['فروش امروز','مجموع تمام فروش امروز را وارد کنید.'],['خرید اجناس','قیمت خرید اجناس برای فروش دوباره را وارد کنید، نه قیمت فروش.'],['مصارف روز','مزد، ترانسپورت، بارگیری، برق، غذا، بسته‌بندی، ترمیم و مصارف روز را وارد کنید.'],['پول ورودی دیگر','پرداخت قرض مشتری یا پول غیر از فروش را وارد کنید.'],['پول خروجی دیگر','قرض داده شد، برداشت تاییدشده یا پول خروجی دیگر را وارد کنید.'],['پول پایان روز','پول نقد موجود را در پایان روز بشمارید و مبلغ دقیق را وارد کنید.'],['بررسی نهایی','تفاوت پول نقد را ببینید؛ اگر صفر نیست دلیل کوتاه بنویسید.']
  ]},
  ps:{title:'ورځنی ثبت',intro:'هر ځل یوه پوښتنه. تر ثبت پورې ځوابونه ساتل کېږي.',locked:'له ثبت وروسته قفل',back:'شاته',next:'بل',submit:'ورځنی ثبت',saving:'ثبتېږي…',progress:'ګام',of:'له',recent:'وروستي ثبتونه',print:'چاپ',salesShort:'پلور',cashShort:'پای نغدې',balanced:'برابر',difference:'توپیر',success:'ورځنی ثبت خوندي شو.',duplicate:'د دې نېټې ثبت شته. له مالک څخه د سمون غوښتنه وکړئ.',review:'وروستی کتل',reviewHelp:'له ثبت مخکې شمېرې وګورئ. وروسته یې یوازې مالک سمولی شي.',expected:'تمه شوې نغدې',actual:'واقعي نغدې',cashDifference:'د نغدو توپیر',notes:'یادښت',notesHelp:'اختیاري: کموالی، نااشنا لګښت، خراب مال یا مهمه پېښه ولیکئ.',notesPlaceholder:'که اړتیا وي لنډ دلیل.',questions:[
    ['نېټه','د کار ورځ وټاکئ؛ عموماً نن.'],['پیل نغدې','هغه نغدې ولیکئ چې د دوکان د پرانیستو پر وخت مو وشمېرلې. مال پکې مه حسابوئ.'],['نننی پلور','د نن ورځې ټول پلور ولیکئ.'],['پېرل شوی مال','د بیا خرڅلاو لپاره د مال د پېر بیه ولیکئ، نه د پلور بیه.'],['ورځني لګښتونه','مزد، ترانسپورټ، بارول، برېښنا، خواړه، بسته‌بندي، ترمیم او نور لګښتونه ولیکئ.'],['نورې داخلې پیسې','د پېرېدونکي د قرض ورکړه یا نورې غیرپلور پیسې ولیکئ.'],['نورې وتلې پیسې','قرض ورکړل شو، تایید شوې ایستنه یا نورې وتلې پیسې ولیکئ.'],['پای نغدې','د ورځې په پای کې موجودې نغدې وشمېرئ او کره مبلغ ولیکئ.'],['وروستی کتل','د نغدو توپیر وګورئ؛ که صفر نه وي لنډ دلیل ولیکئ.']
  ]}
} satisfies Record<AppLanguage,any>;

const fields=['entry_date','opening_cash','sales_revenue','inventory_purchases','operating_expenses','other_money_in','other_money_out','closing_cash'] as const;

export default function DailyWizard({rows,reload}:{rows:Entry[];reload:()=>void}){
  const language=useLanguage(),t=copy[language];
  const[form,setForm]=useState(initial),[step,setStep]=useState(0),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[savedEntry,setSavedEntry]=useState<Entry|null>(null);
  const expected=useMemo(()=>n(form.opening_cash)+n(form.sales_revenue)+n(form.other_money_in)-n(form.inventory_purchases)-n(form.operating_expenses)-n(form.other_money_out),[form]);
  const difference=n(form.closing_cash)-expected;
  const currentField=fields[step];
  const canContinue=step===0?Boolean(form.entry_date):step===8||form[currentField]!=='';
  const change=(key:keyof typeof form,value:string)=>setForm(previous=>({...previous,[key]:value}));
  async function save(){setSaving(true);setMessage('');const{data,error}=await supabase.from('daily_entries').insert({...form,opening_cash:n(form.opening_cash),sales_revenue:n(form.sales_revenue),inventory_purchases:n(form.inventory_purchases),operating_expenses:n(form.operating_expenses),other_money_in:n(form.other_money_in),other_money_out:n(form.other_money_out),closing_cash:n(form.closing_cash)}).select('*, profiles!daily_entries_created_by_fkey(full_name)').single();if(error)setMessage(error.code==='23505'?t.duplicate:error.message);else{setSavedEntry(data as Entry);reload()}setSaving(false)}
  function finish(){setSavedEntry(null);setForm({...initial,entry_date:form.entry_date});setStep(0)}
  if(savedEntry)return <section className="wizard-page"><div className="wizard-card wizard-saved"><CheckCircle2/><h1>{t.success}</h1><p>{t.reviewHelp}</p><strong>{new Date(savedEntry.entry_date+'T00:00:00').toLocaleDateString()} · {money(n(savedEntry.sales_revenue))}</strong><div className="wizard-actions"><button type="button" onClick={()=>printOfficialDailyRecord(savedEntry)}><ReceiptText/>{t.print}</button><button type="button" className="wizard-back" onClick={finish}>{t.back}</button></div></div></section>;
  const input=step===0?<input autoFocus type="date" value={form.entry_date} onChange={e=>change('entry_date',e.target.value)}/>:step<8?<div className="wizard-money"><input autoFocus type="number" min="0" step="0.01" inputMode="decimal" placeholder="0" value={form[currentField]} onChange={e=>change(currentField,e.target.value)}/><span>AFN</span></div>:null;
  return <section className="wizard-page"><header className="wizard-title"><div><p className="eyebrow">2–3 MINUTES</p><h1>{t.title}</h1><p>{t.intro}</p></div><span><ShieldCheck/>{t.locked}</span></header><form className="wizard-card" onSubmit={e=>{e.preventDefault();if(step<8)setStep(step+1);else save()}}><div className="wizard-progress"><div style={{width:`${((step+1)/9)*100}%`}}/><span>{t.progress} {step+1} {t.of} 9</span></div><div className="wizard-question" key={step}><span className="wizard-number">{String(step+1).padStart(2,'0')}</span><h2>{t.questions[step][0]}</h2><p>{t.questions[step][1]}</p>{input}{step===8&&<div className="wizard-review"><div><span>{t.expected}</span><b>{money(expected)}</b></div><div><span>{t.actual}</span><b>{money(n(form.closing_cash))}</b></div><div className={difference===0?'ok':'danger'}><span>{t.cashDifference}</span><b>{money(difference)}</b></div><label>{t.notes}<small>{t.notesHelp}</small><textarea rows={3} value={form.notes} onChange={e=>change('notes',e.target.value)} placeholder={t.notesPlaceholder}/></label></div>}</div>{message&&<p className="notice">{message}</p>}<div className="wizard-actions">{step>0&&<button type="button" className="wizard-back" onClick={()=>setStep(step-1)}><ArrowLeft/>{t.back}</button>}<button disabled={!canContinue||saving}>{step===8?<><FileCheck2/>{saving?t.saving:t.submit}</>:<>{t.next}<ArrowRight/></>}</button></div></form><div className="wizard-history"><h2>{t.recent}</h2>{rows.slice(0,5).map(row=><article key={row.id}><time>{new Date(row.entry_date+'T00:00:00').toLocaleDateString()}</time><div><small>{t.salesShort}</small><b>{money(n(row.sales_revenue))}</b></div><div><small>{t.cashShort}</small><b>{money(n(row.closing_cash))}</b></div><span className={n(row.cash_difference)===0?'ok':'danger'}><CheckCircle2/>{n(row.cash_difference)===0?t.balanced:t.difference}</span><button onClick={()=>printOfficialDailyRecord(row)}><ReceiptText/>{t.print}</button></article>)}</div></section>;
}
