import{useEffect,useMemo,useState}from'react';
import{AlertTriangle,Camera,Check,History,ShieldCheck,X}from'lucide-react';
import{Entry,money,supabase}from'./lib';
import{useLanguage}from'./useLanguage';

type Adjustment={id:string;daily_entry_id:string;reason:string;evidence_path:string;opening_cash_delta:number;sales_revenue_delta:number;inventory_purchases_delta:number;operating_expenses_delta:number;other_money_in_delta:number;other_money_out_delta:number;closing_cash_delta:number;status:'pending'|'approved'|'rejected';submitted_by:string;reviewed_by:string|null;review_note:string;created_at:string;reviewed_at:string|null;original_snapshot:Record<string,unknown>;profiles?:{full_name:string}|null};
const n=(v:unknown)=>Number(v)||0;
const keys=['opening_cash','sales_revenue','inventory_purchases','operating_expenses','other_money_in','other_money_out','closing_cash'] as const;
const labels={opening_cash:'Opening cash',sales_revenue:'Total sales',inventory_purchases:'Inventory purchased',operating_expenses:'Operating expenses',other_money_in:'Qarz received',other_money_out:'Qarz given',closing_cash:'Closing cash'};
const copy={
 en:{title:'Correct a submitted record',intro:'Submitted records cannot be edited or deleted. Request an evidence-backed adjustment instead.',choose:'Choose your record',reason:'Why is this correction necessary?',evidence:'Take correction evidence photo',submit:'Submit correction request',pending:'Awaiting independent owner review',history:'Correction history',review:'Owner review',approve:'Approve adjustment',reject:'Reject adjustment',none:'No correction requests yet.',own:'Only records you submitted in the last 7 days can be corrected.',changed:'Enter the correct values below. Unchanged values stay protected.',saved:'Correction requested. The original record remains unchanged until an independent owner approves it.',same:'Change at least one amount.',photo:'A new supporting photo is required.',self:'The requester cannot approve their own correction.'},
 fa:{title:'اصلاح ثبت‌شده',intro:'ثبت اصلی ویرایش یا حذف نمی‌شود؛ اصلاح با سند جداگانه درخواست کنید.',choose:'ثبت خود را انتخاب کنید',reason:'دلیل اصلاح چیست؟',evidence:'عکس سند اصلاح را بگیرید',submit:'ارسال درخواست اصلاح',pending:'در انتظار بررسی مستقل مالک',history:'تاریخچه اصلاحات',review:'بررسی مالک',approve:'تایید اصلاح',reject:'رد اصلاح',none:'هنوز درخواست اصلاح نیست.',own:'فقط ثبت خود در ۷ روز گذشته قابل اصلاح است.',changed:'مبلغ درست را وارد کنید؛ ارقام بدون تغییر محفوظ می‌ماند.',saved:'درخواست ارسال شد؛ تا تایید مستقل مالک، ثبت اصلی تغییر نمی‌کند.',same:'حداقل یک مبلغ را تغییر دهید.',photo:'عکس تازه سند ضروری است.',self:'درخواست‌کننده نمی‌تواند اصلاح خود را تایید کند.'},
 ps:{title:'د ثبت سمون',intro:'اصلي ثبت نه بدلېږي او نه حذفېږي؛ د سند سره جلا سمون وغواړئ.',choose:'خپل ثبت وټاکئ',reason:'ولې سمون اړین دی؟',evidence:'د سمون د سند عکس واخلئ',submit:'د سمون غوښتنه ولېږئ',pending:'د خپلواک مالک کتنې ته په تمه',history:'د سمون تاریخ',review:'د مالک کتنه',approve:'سمون تایید کړئ',reject:'سمون رد کړئ',none:'تر اوسه د سمون غوښتنه نشته.',own:'یوازې د تېرو ۷ ورځو خپل ثبت سمولای شئ.',changed:'سمې شمېرې ولیکئ؛ نورې شمېرې خوندي پاتې کېږي.',saved:'غوښتنه ولېږل شوه؛ تر خپلواک تایید پورې اصلي ثبت نه بدلېږي.',same:'لږ تر لږه یوه شمېره بدله کړئ.',photo:'د نوي سند عکس اړین دی.',self:'غوښتونکی خپل سمون نشي تاییدولای.'}
};

async function prepare(file:File){const url=URL.createObjectURL(file);try{const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url}),scale=Math.min(1,1800/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not prepare photo.')),'image/jpeg',.86))}finally{URL.revokeObjectURL(url)}}

export default function EntryCorrections({rows,reload}:{rows:Entry[];reload:()=>void}){
 const language=useLanguage(),t=copy[language],[userId,setUserId]=useState(''),[admin,setAdmin]=useState(false),[items,setItems]=useState<Adjustment[]>([]),[selected,setSelected]=useState<Entry|null>(null),[values,setValues]=useState<Record<string,string>>({}),[reason,setReason]=useState(''),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reviewNotes,setReviewNotes]=useState<Record<string,string>>({});
 const eligible=useMemo(()=>rows.filter(r=>r.created_by===userId&&Date.now()-new Date(r.entry_date+'T23:59:59').getTime()<=8*86400000),[rows,userId]);
 async function load(){const[{data:{user}},{data}]=await Promise.all([supabase.auth.getUser(),supabase.from('daily_entry_adjustments').select('*, profiles!daily_entry_adjustments_submitted_by_fkey(full_name)').order('created_at',{ascending:false})]);if(user){setUserId(user.id);const{data:p}=await supabase.from('profiles').select('role').eq('id',user.id).single();setAdmin(p?.role==='admin')}setItems((data||[])as Adjustment[])}
 useEffect(()=>{load();return()=>{if(preview)URL.revokeObjectURL(preview)}},[]);
 function select(entry:Entry){setSelected(entry);setValues(Object.fromEntries(keys.map(k=>[k,String(n(entry[k]))])));setReason('');setPhoto(null);if(preview)URL.revokeObjectURL(preview);setPreview('');setMessage('')}
 function choose(file?:File){if(!file)return;if(preview)URL.revokeObjectURL(preview);setPhoto(file);setPreview(URL.createObjectURL(file));setMessage('')}
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected)return;if(!photo)return setMessage(t.photo);const deltas=Object.fromEntries(keys.map(k=>[`${k}_delta`,n(values[k])-n(selected[k])]));if(Object.values(deltas).every(v=>v===0))return setMessage(t.same);if(reason.trim().length<10)return setMessage(language==='en'?'Please provide a clear reason of at least 10 characters.':language==='fa'?'دلیل روشن حداقل ۱۰ حرف بنویسید.':'لږ تر لږه لس توري روښانه دلیل ولیکئ.');setBusy(true);const image=await prepare(photo),path=`${userId}/${selected.entry_date}/correction-${crypto.randomUUID()}.jpg`,upload=await supabase.storage.from('business-receipts').upload(path,image,{contentType:'image/jpeg'});if(upload.error){setMessage(upload.error.message);setBusy(false);return}const{error}=await supabase.from('daily_entry_adjustments').insert({daily_entry_id:selected.id,reason:reason.trim(),evidence_path:path,submitted_by:userId,...deltas});if(error){await supabase.storage.from('business-receipts').remove([path]);setMessage(error.message)}else{setMessage(t.saved);setSelected(null);setPhoto(null);if(preview)URL.revokeObjectURL(preview);setPreview('');await load()}setBusy(false)}
 async function decide(item:Adjustment,status:'approved'|'rejected'){if(item.submitted_by===userId)return setMessage(t.self);const note=(reviewNotes[item.id]||'').trim();if(!note)return setMessage(language==='en'?'Enter a review note before deciding.':language==='fa'?'پیش از تصمیم یادداشت بررسی بنویسید.':'له پرېکړې مخکې د کتنې یادښت ولیکئ.');setBusy(true);const{error}=await supabase.from('daily_entry_adjustments').update({status,reviewed_by:userId,reviewed_at:new Date().toISOString(),review_note:note}).eq('id',item.id).eq('status','pending');setMessage(error?.message||`Adjustment ${status}.`);if(!error){await load();reload()}setBusy(false)}
 async function evidence(item:Adjustment){const{data,error}=await supabase.storage.from('business-receipts').createSignedUrl(item.evidence_path,300);if(error)setMessage(error.message);else window.open(data.signedUrl,'_blank')}
 return <section className="correction-center"><header><div><p className="eyebrow">IMMUTABLE CORRECTIONS</p><h2>{t.title}</h2><p>{t.intro}</p></div><span><ShieldCheck/>{t.pending}</span></header><p className="correction-rule"><AlertTriangle/>{t.own}</p><div className="correction-layout"><div><label>{t.choose}<select value={selected?.id||''} onChange={e=>select(eligible.find(r=>r.id===e.target.value)!)}><option value="">—</option>{eligible.map(r=><option key={r.id} value={r.id}>{r.entry_date} · {money(n(r.sales_revenue))}</option>)}</select></label>{selected&&<form className="correction-form" onSubmit={submit}><p>{t.changed}</p><div className="wizard-grid">{keys.map(k=><label key={k}>{labels[k]}<div className="wizard-money"><input type="number" min="0" step="0.01" inputMode="decimal" value={values[k]||''} onChange={e=>setValues({...values,[k]:e.target.value})}/><span>AFN</span></div></label>)}</div><label>{t.reason}<textarea required minLength={10} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="camera-only"><Camera/>{t.evidence}<input type="file" accept="image/*" capture="environment" onChange={e=>choose(e.target.files?.[0])}/></label>{preview&&<img className="correction-preview" src={preview} alt="Correction evidence"/>}<button disabled={busy}>{t.submit}</button></form>}</div><div><h3><History/>{admin?t.review:t.history}</h3>{!items.length?<p className="muted">{t.none}</p>:items.map(item=>{const entry=rows.find(r=>r.id===item.daily_entry_id),changes=keys.filter(k=>n(item[`${k}_delta` as keyof Adjustment])!==0);return <article className="correction-item" key={item.id}><header><div><b>{entry?.entry_date||String(item.original_snapshot.entry_date||'')}</b><small>{item.profiles?.full_name||'Approved operator'} · {new Date(item.created_at).toLocaleString()}</small></div><i className={'status '+(item.status==='approved'?'ok':item.status==='rejected'?'danger':'pending')}>{item.status}</i></header><p>{item.reason}</p><div className="correction-deltas">{changes.map(k=><span key={k}>{labels[k]}<b>{n(item[`${k}_delta` as keyof Adjustment])>0?'+':''}{money(n(item[`${k}_delta` as keyof Adjustment]))}</b></span>)}</div><button type="button" className="evidence-button" onClick={()=>evidence(item)}><Camera/>Evidence</button>{admin&&item.status==='pending'&&<div className="correction-review"><textarea rows={2} placeholder="Required independent review note" value={reviewNotes[item.id]||''} onChange={e=>setReviewNotes({...reviewNotes,[item.id]:e.target.value})}/><div><button disabled={busy||item.submitted_by===userId} onClick={()=>decide(item,'approved')}><Check/>{t.approve}</button><button disabled={busy||item.submitted_by===userId} className="reject" onClick={()=>decide(item,'rejected')}><X/>{t.reject}</button></div>{item.submitted_by===userId&&<small>{t.self}</small>}</div>}</article>})}</div></div>{message&&<p className="notice">{message}</p>}</section>
}
