import React, { useEffect, useMemo, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { BarChart3, BookOpen, Check, Clock, LogOut, Menu, ShieldCheck, Users, X } from 'lucide-react'
import type { Session } from '@supabase/supabase-js'
import { configured, Entry, money, Profile, supabase } from './lib'
import './styles.css'

type Page = 'daily'|'monthly'|'quarterly'|'users'
const empty = { entry_date:new Date().toISOString().slice(0,10), opening_cash:'', sales_revenue:'', inventory_purchases:'', operating_expenses:'', other_money_in:'', other_money_out:'', closing_cash:'', notes:'' }

function Auth(){
  const [signup,setSignup]=useState(false), [busy,setBusy]=useState(false), [message,setMessage]=useState('')
  const [form,setForm]=useState({name:'',email:'',password:''})
  async function submit(e:React.FormEvent){ e.preventDefault(); setBusy(true); setMessage('')
    const result=signup ? await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{full_name:form.name},emailRedirectTo:window.location.origin}}) : await supabase.auth.signInWithPassword({email:form.email,password:form.password})
    setMessage(result.error?.message || (signup?'Account created. No email confirmation is needed. Access begins after owner approval.':'')); setBusy(false)
  }
  return <main className="auth"><section className="auth-card"><div className="brand-mark"><BookOpen/></div><p className="eyebrow">BUSINESS RECORDS</p><h1>Keep every afghani accounted for.</h1><p className="muted">Simple daily entries. Clear monthly and quarterly reports.</p><form onSubmit={submit}>{signup&&<label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{message&&<p className="notice">{message}</p>}<button disabled={busy}>{busy?'Please wait…':signup?'Create account':'Log in'}</button></form><button className="link" onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'Already registered? Log in':'New user? Request an account'}</button></section></main>
}

function Waiting({profile}:{profile:Profile}){return <main className="auth"><section className="auth-card center"><Clock size={42}/><h1>{profile.status==='rejected'?'Access not approved':'Approval pending'}</h1><p className="muted">{profile.status==='rejected'?'Contact the business owner if this is unexpected.':'Your account is ready. The business owner must approve it before you can enter or view data.'}</p><button onClick={()=>supabase.auth.signOut()}>Log out</button></section></main>}

function EntryForm({onSaved}:{onSaved:()=>void}){ const [f,setF]=useState(empty),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''); const num=(k:keyof typeof f)=>Number(f[k])||0; const expected=num('opening_cash')+num('sales_revenue')+num('other_money_in')-num('inventory_purchases')-num('operating_expenses')-num('other_money_out'); const difference=num('closing_cash')-expected
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg('');const {error}=await supabase.from('daily_entries').insert({entry_date:f.entry_date,opening_cash:num('opening_cash'),sales_revenue:num('sales_revenue'),inventory_purchases:num('inventory_purchases'),operating_expenses:num('operating_expenses'),other_money_in:num('other_money_in'),other_money_out:num('other_money_out'),closing_cash:num('closing_cash'),notes:f.notes});setMsg(error?.message||'Daily entry saved.');if(!error){setF({...empty,entry_date:f.entry_date});onSaved()}setSaving(false)}
  const field=(key:keyof typeof f,label:string)=><label>{label}<input required type="number" min="0" step="0.01" inputMode="decimal" value={f[key]} onChange={e=>setF({...f,[key]:e.target.value})}/></label>
  return <section><div className="title"><div><p className="eyebrow">TODAY'S RECORD</p><h1>Daily entry</h1></div><span className="secure"><ShieldCheck/> Calculations protected</span></div><form className="entry-card" onSubmit={save}><label>Date<input type="date" required value={f.entry_date} onChange={e=>setF({...f,entry_date:e.target.value})}/></label><div className="grid">{field('opening_cash','Opening cash')}{field('sales_revenue','Sales / revenue')}{field('inventory_purchases','Inventory purchases')}{field('operating_expenses','Operating expenses')}{field('other_money_in','Other money in')}{field('other_money_out','Other money out')}{field('closing_cash','Closing cash')}</div><label>Notes<textarea rows={3} value={f.notes} onChange={e=>setF({...f,notes:e.target.value})} placeholder="Anything the owner should know?"/></label><div className="calcs"><div><span>Expected closing cash</span><strong>{money(expected)}</strong></div><div className={difference===0?'good':'warn'}><span>Cash difference</span><strong>{money(difference)}</strong></div></div>{msg&&<p className="notice">{msg}</p>}<button disabled={saving}>{saving?'Saving…':'Save daily entry'}</button></form></section> }

function Reports({entries,quarterly=false}:{entries:Entry[],quarterly?:boolean}){const groups=useMemo(()=>{const m=new Map<string,Entry[]>();entries.forEach(e=>{const d=new Date(e.entry_date+'T00:00:00');const key=quarterly?`${d.getFullYear()} Q${Math.floor(d.getMonth()/3)+1}`:d.toLocaleDateString('en-US',{year:'numeric',month:'long'});m.set(key,[...(m.get(key)||[]),e])});return [...m]},[entries,quarterly]);return <section><div className="title"><div><p className="eyebrow">PROTECTED REPORT</p><h1>{quarterly?'Quarterly':'Monthly'} summary</h1></div></div>{groups.length===0?<div className="empty">No entries yet.</div>:groups.map(([name,rows])=>{const sum=(k:keyof Entry)=>rows.reduce((a,e)=>a+Number(e[k]||0),0);const profit=sum('sales_revenue')+sum('other_money_in')-sum('inventory_purchases')-sum('operating_expenses')-sum('other_money_out');return <article className="report" key={name}><h2>{name}</h2><div className="metrics"><div><span>Revenue</span><b>{money(sum('sales_revenue'))}</b></div><div><span>Purchases</span><b>{money(sum('inventory_purchases'))}</b></div><div><span>Expenses</span><b>{money(sum('operating_expenses'))}</b></div><div className={profit>=0?'good':'warn'}><span>Net movement</span><b>{money(profit)}</b></div></div><small>{rows.length} daily record{rows.length===1?'':'s'}</small></article>})}</section>}

function UsersPage(){const [users,setUsers]=useState<Profile[]>([]);async function load(){const {data}=await supabase.from('profiles').select('*').order('created_at');setUsers(data||[])}useEffect(()=>{load()},[]);async function setStatus(id:string,status:'approved'|'rejected'){await supabase.from('profiles').update({status}).eq('id',id);load()}return <section><div className="title"><div><p className="eyebrow">OWNER CONTROL</p><h1>User approvals</h1></div></div><div className="users">{users.map(u=><article key={u.id}><div><strong>{u.full_name||'Unnamed user'}</strong><span>{u.email}</span><small>{u.role} · {u.status}</small></div>{u.role!=='admin'&&<div className="actions"><button className="approve" onClick={()=>setStatus(u.id,'approved')}><Check/>Approve</button><button className="reject" onClick={()=>setStatus(u.id,'rejected')}><X/>Reject</button></div>}</article>)}</div></section>}

function App(){const [session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[page,setPage]=useState<Page>('daily'),[entries,setEntries]=useState<Entry[]>([]),[menu,setMenu]=useState(false)
  async function loadProfile(userId:string){const {data}=await supabase.from('profiles').select('*').eq('id',userId).single();setProfile(data);setLoading(false)} async function loadEntries(){const {data}=await supabase.from('daily_entries').select('*').order('entry_date',{ascending:false});setEntries(data||[])}
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadProfile(data.session.user.id);else setLoading(false)});const {data:s}=supabase.auth.onAuthStateChange((_e,x)=>{setSession(x);if(x)loadProfile(x.user.id);else{setProfile(null);setLoading(false)}});return()=>s.subscription.unsubscribe()},[])
  useEffect(()=>{if(profile?.status==='approved')loadEntries()},[profile])
  if(!configured)return <main className="auth"><section className="auth-card"><h1>Setup needed</h1><p>Add the Supabase URL and publishable key to the environment file. See README.md.</p></section></main>; if(loading)return <main className="auth">Loading…</main>;if(!session)return <Auth/>;if(!profile||profile.status!=='approved')return profile?<Waiting profile={profile}/>:<main className="auth">Preparing account…</main>
  const nav:[Page,string,React.ReactNode][]=[['daily','Daily entry',<BookOpen/>],['monthly','Monthly',<BarChart3/>],['quarterly','Quarterly',<BarChart3/>],...(profile.role==='admin'?[['users','Users',<Users/>] as [Page,string,React.ReactNode]]:[])];return <div className="shell"><aside className={menu?'open':''}><div className="side-brand"><div className="brand-mark"><BookOpen/></div><b>Business Ledger</b></div><nav>{nav.map(([p,l,i])=><button className={page===p?'active':''} key={p} onClick={()=>{setPage(p);setMenu(false)}}>{i}{l}</button>)}</nav><div className="account"><small>Signed in as</small><b>{profile.full_name}</b><button onClick={()=>supabase.auth.signOut()}><LogOut/>Log out</button></div></aside><main className="content"><button className="menu" onClick={()=>setMenu(!menu)}><Menu/></button>{page==='daily'&&<EntryForm onSaved={loadEntries}/>} {page==='monthly'&&<Reports entries={entries}/>} {page==='quarterly'&&<Reports entries={entries} quarterly/>} {page==='users'&&<UsersPage/>}</main></div>}

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
