import{useMemo,useState}from'react';
import{ArrowLeft,ArrowRight,BarChart3,CalendarClock,CheckCircle2,PackageCheck,ShieldCheck}from'lucide-react';
import{Entry,money,MonthlyClose,supabase}from'./lib';
import{AppLanguage,useLanguage}from'./useLanguage';

const today=new Date().toISOString().slice(0,10),n=(v:unknown)=>Number(v)||0,month=(d:string)=>d.slice(0,7),sum=(rows:Entry[],key:keyof Entry)=>rows.reduce((a,r)=>a+n(r[key]),0);
type Form={month_start:string;beginning_inventory:string;ending_inventory:string;rent:string;salaries:string;utilities:string;transport:string;other_expenses:string;closing_cash:string;receivables:string;payables:string;notes:string};
const fresh=():Form=>({month_start:today.slice(0,7)+'-01',beginning_inventory:'',ending_inventory:'',rent:'',salaries:'',utilities:'',transport:'',other_expenses:'',closing_cash:'',receivables:'',payables:'',notes:''});
const copy={
en:{title:'Monthly close',intro:'After the last daily record. Known numbers fill automatically.',start:'Start monthly close',cancel:'Cancel',back:'Back',next:'Next',save:'Finish and protect month',saving:'Saving…',step:'Step',of:'of',saved:'Month closed. Profit and customer Qarz are protected.',reports:'Protected monthly reports',empty:'No monthly close yet.',sales:'Total sales',purchases:'Inventory purchases',daily:'Daily operating expenses',given:'Qarz given',received:'Qarz received',cogs:'Cost of goods sold',gross:'Gross profit',net:'Net profit',inventory:'Ending inventory',cash:'Closing cash',receivables:'Customer Qarz owed',payables:'Business payables',auto:'Calculated by system',noRows:'No daily records exist for this month. Save them before closing.',first:'First month only: enter this because there is no previous close.',steps:[['Choose month','The system reads every saved daily record.'],['Count inventory','Beginning inventory comes from the previous close. Count unsold goods at purchase cost.'],['Monthly-only costs','Enter rent, salaries and monthly bills. Never repeat daily expenses.'],['Cash and debts','Closing cash and customer Qarz calculate automatically. Enter only business payables.'],['Review and close','Check automatic and manual values, then protect the month.']]},
fa:{title:'بستن ماهانه',intro:'پس از آخرین ثبت روزانه؛ ارقام موجود خودکار درج می‌شود.',start:'شروع بستن ماه',cancel:'لغو',back:'قبلی',next:'بعدی',save:'تکمیل و محافظت ماه',saving:'در حال ثبت…',step:'مرحله',of:'از',saved:'ماه بسته شد؛ سود و قرض مشتریان محفوظ شد.',reports:'گزارش‌های ماهانه محفوظ',empty:'هنوز ماه بسته نشده است.',sales:'مجموع فروش',purchases:'خرید اجناس',daily:'مصارف روزانه',given:'قرض داده شد',received:'قرض وصول شد',cogs:'بهای جنس فروخته‌شده',gross:'سود ناخالص',net:'سود خالص',inventory:'موجودی پایان',cash:'پول نقد پایان',receivables:'قرض مشتریان',payables:'بدهی تجارت',auto:'محاسبه خودکار',noRows:'این ماه ثبت روزانه ندارد. نخست ثبت‌های روزانه را ذخیره کنید.',first:'فقط ماه اول: چون ماه قبلی موجود نیست، این مبلغ را وارد کنید.',steps:[['انتخاب ماه','سیستم همه ثبت‌های روزانه را می‌خواند.'],['شمارش موجودی','موجودی آغاز از ماه قبل می‌آید؛ جنس باقی‌مانده را به قیمت خرید بشمارید.'],['مصارف ماهانه','کرایه، معاش و بل‌های ماه را وارد کنید؛ مصرف روزانه را تکرار نکنید.'],['پول و قرض','پول پایان و قرض مشتریان خودکار است؛ فقط بدهی تجارت را وارد کنید.'],['بررسی و بستن','ارقام خودکار و دستی را بررسی و ماه را محافظت کنید.']]},
ps:{title:'میاشتنی تړون',intro:'د وروستي ورځني ثبت وروسته؛ معلوم شمېرې پخپله راځي.',start:'میاشت وتړئ',cancel:'لغوه',back:'شاته',next:'بل',save:'میاشت ختمه او خوندي کړئ',saving:'ثبتېږي…',step:'ګام',of:'له',saved:'میاشت وتړل شوه؛ ګټه او د پېرېدونکو پور خوندي شو.',reports:'خوندي میاشتني راپورونه',empty:'میاشت لا نه ده تړل شوې.',sales:'ټول پلور',purchases:'پېرل شوی مال',daily:'ورځني لګښتونه',given:'پور ورکړل شو',received:'پور ترلاسه شو',cogs:'د خرڅ شوي مال بیه',gross:'ناخالصه ګټه',net:'خالصه ګټه',inventory:'پای مال',cash:'پای نغدې',receivables:'د پېرېدونکو پور',payables:'د کاروبار پور',auto:'سیستم حساب کړی',noRows:'په دې میاشت کې ورځنی ثبت نشته. لومړی یې خوندي کړئ.',first:'یوازې لومړۍ میاشت: د تېر تړون د نشتون له امله دا ولیکئ.',steps:[['میاشت','سیستم ټول ورځني ثبتونه پخپله لولي.'],['د مال شمېر','پیل مال له تېرې میاشتې راځي؛ پاتې مال د پېر په بیه وشمېرئ.'],['میاشتني لګښتونه','کرایه، معاش او میاشتني بلونه ولیکئ؛ ورځنی لګښت مه تکراروئ.'],['نغدې او پور','پای نغدې او د خلکو پور پخپله حسابېږي؛ یوازې د کاروبار پور ولیکئ.'],['کتل او تړل','اتومات او خپل شمېرې وګورئ او میاشت خوندي کړئ.']]}
} satisfies Record<AppLanguage,any>;

export default function MonthPage({d,manage,reload}:{d:{entries:Entry[];closes:MonthlyClose[]};manage:boolean;reload:()=>void}){
 const language=useLanguage(),t=copy[language],[open,setOpen]=useState(false),[step,setStep]=useState(0),[form,setForm]=useState<Form>(fresh),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 const rows=d.entries.filter(x=>month(x.entry_date)===month(form.month_start)).sort((a,b)=>a.entry_date.localeCompare(b.entry_date)),previous=[...d.closes].filter(c=>c.month_start<form.month_start).sort((a,b)=>b.month_start.localeCompare(a.month_start))[0],latest=rows.at(-1);
 const sales=sum(rows,'sales_revenue'),purchases=sum(rows,'inventory_purchases'),dailyCosts=sum(rows,'operating_expenses'),given=sum(rows,'other_money_out'),received=sum(rows,'other_money_in'),beginning=previous?n(previous.ending_inventory):n(form.beginning_inventory),closingCash=latest?n(latest.closing_cash):n(form.closing_cash),customerQarz=(previous?n(previous.receivables):n(form.receivables))+given-received;
 const change=(key:keyof Form,value:string)=>setForm(f=>({...f,[key]:value}));
 const Auto=({label,value,plain=false}:{label:string;value:number;plain?:boolean})=><div className="auto-value"><span>{label}<small>{plain?'':t.auto}</small></span><b>{plain?value:money(value)}</b></div>;
 const groups=useMemo(()=>[
  <div><label>Month<input type="month" value={form.month_start.slice(0,7)} onChange={e=>change('month_start',e.target.value+'-01')}/></label><div className="month-preview"><Auto label={language==='en'?'Daily records':language==='fa'?'ثبت‌های روزانه':'ورځني ثبتونه'} value={rows.length} plain/><Auto label={t.sales} value={sales}/><Auto label={t.purchases} value={purchases}/><Auto label={t.daily} value={dailyCosts}/></div>{!rows.length&&<p className="notice">{t.noRows}</p>}</div>,
  <div className="wizard-grid">{previous?<Auto label={language==='en'?'Beginning inventory':language==='fa'?'موجودی آغاز':'پیل مال'} value={beginning}/>:<Money label={language==='en'?'Beginning inventory':language==='fa'?'موجودی آغاز':'پیل مال'} help={t.first} value={form.beginning_inventory} set={v=>change('beginning_inventory',v)}/>}<Money label={t.inventory} help={language==='en'?'Count unsold goods at purchase cost.':language==='fa'?'جنس باقی‌مانده را به قیمت خرید بشمارید.':'پاتې مال د پېر په بیه وشمېرئ.'} value={form.ending_inventory} set={v=>change('ending_inventory',v)}/></div>,
  <div className="wizard-grid"><Money label="Rent / کرایه" value={form.rent} set={v=>change('rent',v)}/><Money label="Salaries / معاش" value={form.salaries} set={v=>change('salaries',v)}/><Money label="Utilities" value={form.utilities} set={v=>change('utilities',v)}/><Money label="Transport" value={form.transport} set={v=>change('transport',v)}/><Money label="Other monthly expenses" value={form.other_expenses} set={v=>change('other_expenses',v)}/></div>,
  <div><div className="month-preview">{latest?<Auto label={t.cash} value={closingCash}/>:<Money label={t.cash} value={form.closing_cash} set={v=>change('closing_cash',v)}/>} {previous?<Auto label={t.receivables} value={customerQarz}/>:<Money label={language==='en'?'Opening customer Qarz':language==='fa'?'قرض مشتریان در آغاز ماه':'د میاشتې په پیل کې د پېرېدونکو پور'} help={t.first} value={form.receivables} set={v=>change('receivables',v)}/>}<Auto label={t.given} value={given}/><Auto label={t.received} value={received}/><Auto label={t.receivables} value={customerQarz}/></div><Money label={t.payables} help={language==='en'?'What the business owes suppliers or others.':language==='fa'?'مبلغی که تجارت به دیگران بدهکار است.':'هغه پیسې چې کاروبار نورو ته پوروړی دی.'} value={form.payables} set={v=>change('payables',v)}/></div>,
  <div className="month-preview"><Auto label={t.sales} value={sales}/><Auto label={t.purchases} value={purchases}/><Auto label={t.daily} value={dailyCosts}/><Auto label={t.given} value={given}/><Auto label={t.received} value={received}/><Auto label={t.receivables} value={customerQarz}/><label>Month-end notes<textarea rows={3} value={form.notes} onChange={e=>change('notes',e.target.value)}/></label></div>
 ],[form,language,sales,purchases,dailyCosts,given,received,beginning,closingCash,customerQarz,previous,latest,rows.length]);
 async function save(){if(!rows.length)return setMessage(t.noRows);setSaving(true);const payload={...form,beginning_inventory:beginning,ending_inventory:n(form.ending_inventory),rent:n(form.rent),salaries:n(form.salaries),utilities:n(form.utilities),transport:n(form.transport),other_expenses:n(form.other_expenses),closing_cash:closingCash,receivables:customerQarz,payables:n(form.payables)};const{error}=await supabase.from('monthly_closes').insert(payload);setMessage(error?.message||t.saved);if(!error){setOpen(false);setStep(0);setForm(fresh());reload()}setSaving(false)}
 return <section className="wizard-page"><header className="wizard-title"><div><p className="eyebrow">MONTH-END CONTROL</p><h1>{t.title}</h1><p>{t.intro}</p></div>{manage&&<button onClick={()=>{setOpen(!open);setStep(0)}}>{open?t.cancel:t.start}</button>}</header>{open&&<form className="wizard-card month-wizard" onSubmit={e=>{e.preventDefault();step<4?setStep(step+1):save()}}><div className="wizard-progress"><div style={{width:`${((step+1)/5)*100}%`}}/><span>{t.step} {step+1} {t.of} 5</span></div><div className="wizard-question" key={step}><span className="wizard-number">{String(step+1).padStart(2,'0')}</span><h2>{t.steps[step][0]}</h2><p>{t.steps[step][1]}</p>{groups[step]}</div><div className="wizard-actions">{step>0&&<button type="button" className="wizard-back" onClick={()=>setStep(step-1)}><ArrowLeft/>{t.back}</button>}<button disabled={saving||step===0&&!rows.length}>{step===4?<><ShieldCheck/>{saving?t.saving:t.save}</>:<>{t.next}<ArrowRight/></>}</button></div></form>}{message&&<p className="notice">{message}</p>}<div className="close-guide"><CalendarClock/><div><b>{language==='en'?'When to close':language==='fa'?'زمان بستن':'د تړلو وخت'}</b><span>{t.intro}</span></div><PackageCheck/><div><b>{language==='en'?'What changes':language==='fa'?'نتیجه':'پایله'}</b><span>{t.steps[4][1]}</span></div></div><div className="report-list month-reports"><h2>{t.reports}</h2>{!d.closes.length?<div className="empty"><BarChart3/><p>{t.empty}</p></div>:d.closes.map(c=>{const r=d.entries.filter(x=>month(x.entry_date)===month(c.month_start)),s=sum(r,'sales_revenue'),buy=sum(r,'inventory_purchases'),ops=sum(r,'operating_expenses')+n(c.rent)+n(c.salaries)+n(c.utilities)+n(c.transport)+n(c.other_expenses),cogs=n(c.beginning_inventory)+buy-n(c.ending_inventory),gross=s-cogs,net=gross-ops;return <article className="report-card" key={c.id}><header><h2>{new Date(c.month_start+'T00:00:00').toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><span className="status ok"><CheckCircle2/> {c.status}</span></header><div className="report-metrics"><div><span>{t.sales}</span><b>{money(s)}</b></div><div><span>{t.cogs}</span><b>{money(cogs)}</b></div><div><span>{t.gross}</span><b>{money(gross)}</b></div><div className={net>=0?'ok':'danger'}><span>{t.net}</span><b>{money(net)}</b></div></div><div className="statement"><span>{t.inventory}<b>{money(n(c.ending_inventory))}</b></span><span>{t.cash}<b>{money(n(c.closing_cash))}</b></span><span>{t.receivables}<b>{money(n(c.receivables))}</b></span><span>{t.payables}<b>{money(n(c.payables))}</b></span></div></article>})}</div></section>
}
function Money({label,help,value,set}:{label:string;help?:string;value:string;set:(v:string)=>void}){return <label>{label}{help&&<small>{help}</small>}<div className="wizard-money"><input type="number" min="0" step="0.01" inputMode="decimal" placeholder="0" value={value} onChange={e=>set(e.target.value)}/><span>AFN</span></div></label>}
