import{useMemo,useState}from'react';
import{ArrowLeft,ArrowRight,BarChart3,CalendarClock,CheckCircle2,PackageCheck,ShieldCheck}from'lucide-react';
import{Entry,money,MonthlyClose,supabase}from'./lib';
import{AppLanguage,useLanguage}from'./useLanguage';

const today=new Date().toISOString().slice(0,10),n=(v:unknown)=>Number(v)||0,month=(d:string)=>d.slice(0,7),sum=(rows:Entry[],key:keyof Entry)=>rows.reduce((a,r)=>a+n(r[key]),0);
type Form={month_start:string;beginning_inventory:string;ending_inventory:string;rent:string;salaries:string;utilities:string;transport:string;other_expenses:string;closing_cash:string;receivables:string;payables:string;notes:string};
const fresh=():Form=>({month_start:today.slice(0,7)+'-01',beginning_inventory:'',ending_inventory:'',rent:'',salaries:'',utilities:'',transport:'',other_expenses:'',closing_cash:'',receivables:'',payables:'',notes:''});
const text={
 en:{title:'Monthly close',intro:'Do this once after the last business day of each month.',start:'Start monthly close',cancel:'Cancel',back:'Back',next:'Next',save:'Finish and protect month',saving:'Saving…',step:'Step',of:'of',saved:'Monthly close saved. The system can now calculate profit for this month.',reports:'Protected monthly reports',empty:'No monthly close yet.',sales:'Sales',cogs:'Cost of goods sold',gross:'Gross profit',net:'Net profit',inventory:'Ending inventory',cash:'Closing cash',receivables:'Receivables',payables:'Payables',steps:[
  ['Choose month','Select the month only after its final daily entry has been saved.'],['Count inventory','Count unsold goods carefully. Use purchase cost—not selling price. Beginning inventory should match last month’s ending inventory.'],['Record monthly costs','Enter costs not already recorded in daily expenses. Do not enter the same expense twice.'],['Cash and debts','Count month-end cash. Record money customers owe you and money the business owes others.'],['Review and close','After you finish, inventory cost, gross profit and net profit become protected monthly results. Check every amount first.']
 ]},
 fa:{title:'بستن ماهانه',intro:'یک بار پس از آخرین روز کاری ماه انجام دهید.',start:'شروع بستن ماه',cancel:'لغو',back:'قبلی',next:'بعدی',save:'تکمیل و محافظت ماه',saving:'در حال ثبت…',step:'مرحله',of:'از',saved:'ماه بسته شد. اکنون سود ماه محاسبه می‌شود.',reports:'گزارش‌های ماهانه محفوظ',empty:'هنوز ماه بسته نشده است.',sales:'فروش',cogs:'بهای جنس فروخته‌شده',gross:'سود ناخالص',net:'سود خالص',inventory:'موجودی پایان',cash:'پول نقد پایان',receivables:'طلب‌ها',payables:'بدهی‌ها',steps:[['انتخاب ماه','پس از ثبت آخرین گزارش روزانه، ماه را انتخاب کنید.'],['شمارش موجودی','اجناس باقی‌مانده را به قیمت خرید بشمارید، نه قیمت فروش. موجودی آغاز باید با پایان ماه قبل برابر باشد.'],['مصارف ماه','فقط مصارفی را وارد کنید که در ثبت روزانه نیامده‌اند. یک مصرف را دوبار ثبت نکنید.'],['پول و قرض‌ها','پول پایان ماه، طلب مشتریان و بدهی تجارت را ثبت کنید.'],['بررسی و بستن','پس از تکمیل، بهای جنس، سود ناخالص و سود خالص محافظت می‌شود. نخست همه ارقام را بررسی کنید.']]},
 ps:{title:'میاشتنی تړون',intro:'د میاشتې له وروستۍ کاري ورځې وروسته یو ځل.',start:'میاشت وتړئ',cancel:'لغوه',back:'شاته',next:'بل',save:'میاشت ختمه او خوندي کړئ',saving:'ثبتېږي…',step:'ګام',of:'له',saved:'میاشت وتړل شوه. اوس ګټه حسابېږي.',reports:'خوندي میاشتني راپورونه',empty:'میاشت لا نه ده تړل شوې.',sales:'پلور',cogs:'د خرڅ شوي مال بیه',gross:'ناخالصه ګټه',net:'خالصه ګټه',inventory:'پای مال',cash:'پای نغدې',receivables:'طلبونه',payables:'پورونه',steps:[['میاشت','د وروستي ورځني ثبت وروسته میاشت وټاکئ.'],['د مال شمېر','پاتې مال د پېر په بیه وشمېرئ، نه د پلور. د پیل مال دې د تېرې میاشتې له پای سره برابر وي.'],['میاشتني لګښتونه','یوازې هغه لګښتونه ولیکئ چې ورځني ثبت کې نه دي. یو لګښت دوه ځله مه لیکئ.'],['نغدې او پور','د میاشتې پای نغدې، د خلکو پور او د کاروبار پور ولیکئ.'],['کتل او تړل','وروسته د مال بیه او ګټه خوندي حسابېږي. لومړی ټولې شمېرې وګورئ.']]}
} satisfies Record<AppLanguage,any>;

export default function MonthPage({d,manage,reload}:{d:{entries:Entry[];closes:MonthlyClose[]};manage:boolean;reload:()=>void}){
 const language=useLanguage(),t=text[language],[open,setOpen]=useState(false),[step,setStep]=useState(0),[form,setForm]=useState<Form>(fresh),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 const rows=d.entries.filter(x=>month(x.entry_date)===month(form.month_start)),sales=sum(rows,'sales_revenue'),purchases=sum(rows,'inventory_purchases'),dailyCosts=sum(rows,'operating_expenses')+sum(rows,'other_money_out');
 const change=(key:keyof Form,value:string)=>setForm(f=>({...f,[key]:value}));
 const groups=useMemo(()=>[
  <label>Month<input type="month" value={form.month_start.slice(0,7)} onChange={e=>change('month_start',e.target.value+'-01')}/></label>,
  <div className="wizard-grid"><Money label="Beginning inventory" value={form.beginning_inventory} set={v=>change('beginning_inventory',v)}/><Money label="Ending inventory" value={form.ending_inventory} set={v=>change('ending_inventory',v)}/></div>,
  <div className="wizard-grid"><Money label="Rent" value={form.rent} set={v=>change('rent',v)}/><Money label="Salaries" value={form.salaries} set={v=>change('salaries',v)}/><Money label="Utilities" value={form.utilities} set={v=>change('utilities',v)}/><Money label="Transport" value={form.transport} set={v=>change('transport',v)}/><Money label="Other expenses" value={form.other_expenses} set={v=>change('other_expenses',v)}/></div>,
  <div className="wizard-grid"><Money label="Closing cash" value={form.closing_cash} set={v=>change('closing_cash',v)}/><Money label="Receivables" value={form.receivables} set={v=>change('receivables',v)}/><Money label="Payables" value={form.payables} set={v=>change('payables',v)}/></div>,
  <div className="month-preview"><div><span>{t.sales}</span><b>{money(sales)}</b></div><div><span>Purchases</span><b>{money(purchases)}</b></div><div><span>Daily costs</span><b>{money(dailyCosts)}</b></div><label>Month-end notes<textarea rows={3} value={form.notes} onChange={e=>change('notes',e.target.value)}/></label></div>
 ],[form,language,sales,purchases,dailyCosts]);
 async function save(){setSaving(true);const payload=Object.fromEntries(Object.entries(form).map(([k,v])=>['notes','month_start'].includes(k)?[k,v]:[k,n(v)]));const{error}=await supabase.from('monthly_closes').insert(payload);setMessage(error?.message||t.saved);if(!error){setOpen(false);setStep(0);setForm(fresh());reload()}setSaving(false)}
 return <section className="wizard-page"><header className="wizard-title"><div><p className="eyebrow">MONTH-END CONTROL</p><h1>{t.title}</h1><p>{t.intro}</p></div>{manage&&<button onClick={()=>{setOpen(!open);setStep(0)}}>{open?t.cancel:t.start}</button>}</header>{open&&<form className="wizard-card month-wizard" onSubmit={e=>{e.preventDefault();step<4?setStep(step+1):save()}}><div className="wizard-progress"><div style={{width:`${((step+1)/5)*100}%`}}/><span>{t.step} {step+1} {t.of} 5</span></div><div className="wizard-question" key={step}><span className="wizard-number">{String(step+1).padStart(2,'0')}</span><h2>{t.steps[step][0]}</h2><p>{t.steps[step][1]}</p>{groups[step]}</div><div className="wizard-actions">{step>0&&<button type="button" className="wizard-back" onClick={()=>setStep(step-1)}><ArrowLeft/>{t.back}</button>}<button disabled={saving}>{step===4?<><ShieldCheck/>{saving?t.saving:t.save}</>:<>{t.next}<ArrowRight/></>}</button></div></form>}{message&&<p className="notice">{message}</p>}<div className="close-guide"><CalendarClock/><div><b>{language==='en'?'When to close':language==='fa'?'زمان بستن':'د تړلو وخت'}</b><span>{t.intro}</span></div><PackageCheck/><div><b>{language==='en'?'What changes':language==='fa'?'نتیجه':'پایله'}</b><span>{t.steps[4][1]}</span></div></div><div className="report-list month-reports"><h2>{t.reports}</h2>{d.closes.length===0?<div className="empty"><BarChart3/><p>{t.empty}</p></div>:d.closes.map(c=>{const monthRows=d.entries.filter(x=>month(x.entry_date)===month(c.month_start)),monthSales=sum(monthRows,'sales_revenue'),buy=sum(monthRows,'inventory_purchases'),ops=sum(monthRows,'operating_expenses')+sum(monthRows,'other_money_out')+n(c.rent)+n(c.salaries)+n(c.utilities)+n(c.transport)+n(c.other_expenses),cogs=n(c.beginning_inventory)+buy-n(c.ending_inventory),gross=monthSales-cogs,net=gross-ops;return <article className="report-card" key={c.id}><header><h2>{new Date(c.month_start+'T00:00:00').toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><span className="status ok"><CheckCircle2/> {c.status}</span></header><div className="report-metrics"><div><span>{t.sales}</span><b>{money(monthSales)}</b></div><div><span>{t.cogs}</span><b>{money(cogs)}</b></div><div><span>{t.gross}</span><b>{money(gross)}</b></div><div className={net>=0?'ok':'danger'}><span>{t.net}</span><b>{money(net)}</b></div></div><div className="statement"><span>{t.inventory}<b>{money(n(c.ending_inventory))}</b></span><span>{t.cash}<b>{money(n(c.closing_cash))}</b></span><span>{t.receivables}<b>{money(n(c.receivables))}</b></span><span>{t.payables}<b>{money(n(c.payables))}</b></span></div></article>})}</div></section>
}

function Money({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return <label>{label}<div className="wizard-money"><input autoFocus type="number" min="0" step="0.01" inputMode="decimal" placeholder="0" value={value} onChange={e=>set(e.target.value)}/><span>AFN</span></div></label>}
