import{BarChart3,CalendarCheck2,CheckCircle2,ClipboardCheck,WalletCards}from'lucide-react';
import type{ReactNode}from'react';
import{Entry,money,QuarterlyReview}from'./lib';
import{AppLanguage,useLanguage}from'./useLanguage';

const n=(v:unknown)=>Number(v)||0,sum=(rows:Entry[],key:keyof Entry)=>rows.reduce((a,r)=>a+n(r[key]),0);
const copy={
 en:{title:'Quarterly review',intro:'Review the business after every three completed months.',when:'When',whenText:'After March, June, September and December—once all three monthly closes are complete.',check:'What to check',checkText:'Profit trend, cash differences, unsold inventory, customer qarz, business debts and partner money.',result:'What happens',resultText:'The owner and partners record decisions. The protected daily and monthly records do not change.',ready:'Before the meeting',readyText:'Confirm all daily entries, receipts and three monthly closes. Investigate unexplained cash differences.',records:'daily records',revenue:'Revenue',outflows:'Cash outflows',movement:'Net movement',retained:'Profit retained',decision:'Partner decision'},
 fa:{title:'گزارش سه‌ماهه',intro:'پس از هر سه ماه تکمیل‌شده تجارت را بررسی کنید.',when:'زمان',whenText:'پس از مارچ، جون، سپتامبر و دسمبر؛ وقتی هر سه ماه بسته شده باشد.',check:'چه چیز بررسی شود',checkText:'روند سود، تفاوت پول، موجودی، قرض مشتری، بدهی تجارت و پول شرکا.',result:'نتیجه',resultText:'مالک و شرکا تصمیم‌ها را ثبت می‌کنند. ثبت‌های محفوظ تغییر نمی‌کند.',ready:'پیش از جلسه',readyText:'ثبت‌های روزانه، رسیدها و سه بستن ماهانه را تکمیل کنید. تفاوت پول را بررسی کنید.',records:'ثبت روزانه',revenue:'عاید',outflows:'پول خروجی',movement:'تغییر خالص',retained:'سود نگهداری‌شده',decision:'تصمیم شرکا'},
 ps:{title:'درې‌میاشتنی راپور',intro:'له هرو دریو بشپړو میاشتو وروسته کاروبار وګورئ.',when:'وخت',whenText:'د مارچ، جون، سپتمبر او دسمبر وروسته؛ چې درې میاشتې تړل شوې وي.',check:'څه وګورئ',checkText:'ګټه، د نغدو توپیر، پاتې مال، د پېرېدونکي قرض، د کاروبار پور او د شریکانو پیسې.',result:'پایله',resultText:'مالک او شریکان پرېکړې ثبتوي. خوندي ثبتونه نه بدلېږي.',ready:'له غونډې مخکې',readyText:'ورځني ثبتونه، رسیدونه او درې میاشتني تړونونه بشپړ کړئ. د نغدو توپیر وڅېړئ.',records:'ورځني ثبتونه',revenue:'عاید',outflows:'وتلې پیسې',movement:'خالص بدلون',retained:'ساتل شوې ګټه',decision:'د شریکانو پرېکړه'}
} satisfies Record<AppLanguage,any>;

export default function Quarter({d}:{d:{entries:Entry[];reviews:QuarterlyReview[]}}){const language=useLanguage(),t=copy[language],year=new Date().getFullYear();return <section><header className="wizard-title"><div><p className="eyebrow">PARTNER REVIEW</p><h1>{t.title}</h1><p>{t.intro}</p></div><span><WalletCards/>{year}</span></header><div className="quarter-guide"><Guide icon={<CalendarCheck2/>} title={t.when} body={t.whenText}/><Guide icon={<BarChart3/>} title={t.check} body={t.checkText}/><Guide icon={<CheckCircle2/>} title={t.result} body={t.resultText}/><Guide icon={<ClipboardCheck/>} title={t.ready} body={t.readyText}/></div><div className="report-list">{[1,2,3,4].map(q=>{const rows=d.entries.filter(x=>{const date=new Date(x.entry_date+'T00:00:00');return date.getFullYear()===year&&Math.floor(date.getMonth()/3)+1===q}),sales=sum(rows,'sales_revenue'),out=sum(rows,'inventory_purchases')+sum(rows,'operating_expenses')+sum(rows,'other_money_out'),review=d.reviews.find(x=>x.year===year&&x.quarter===q);return <article className="report-card" key={q}><header><div><p className="eyebrow">{year}</p><h2>Q{q}</h2></div><span>{rows.length} {t.records}</span></header><div className="report-metrics"><div><span>{t.revenue}</span><b>{money(sales)}</b></div><div><span>{t.outflows}</span><b>{money(out)}</b></div><div><span>{t.movement}</span><b>{money(sales-out)}</b></div><div><span>{t.retained}</span><b>{money(n(review?.retained_profit))}</b></div></div>{review&&<p className="decision"><b>{t.decision}:</b> {review.major_decisions||'—'}</p>}</article>})}</div></section>}

function Guide({icon,title,body}:{icon:ReactNode;title:string;body:string}){return <article>{icon}<div><b>{title}</b><p>{body}</p></div></article>}
