create type public.partner_transaction_type as enum ('capital_contribution','partner_withdrawal','partner_loan_in','loan_repayment','profit_distribution');
create table public.partner_transactions(id uuid primary key default gen_random_uuid(),partner_id uuid not null references public.partners(id),transaction_date date not null default current_date,transaction_type public.partner_transaction_type not null,amount_afn numeric(14,2) not null check(amount_afn>0),notes text not null default '' check(char_length(notes)<=2000),status public.approval_status not null default 'pending',submitted_by uuid not null default auth.uid() references public.profiles(id),approved_by uuid references public.profiles(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index partner_transactions_partner_idx on public.partner_transactions(partner_id,transaction_date desc);
create index partner_transactions_submitter_idx on public.partner_transactions(submitted_by);
create index partner_transactions_approver_idx on public.partner_transactions(approved_by);
create table public.activity_messages(id uuid primary key default gen_random_uuid(),message text not null check(char_length(message) between 1 and 2000),created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now());
create index activity_messages_created_idx on public.activity_messages(created_at desc);
create index activity_messages_creator_idx on public.activity_messages(created_by);
alter table public.partner_transactions enable row level security;
alter table public.activity_messages enable row level security;
create policy "approved_partner_transactions_read" on public.partner_transactions for select to authenticated using((select private.is_approved()));
create policy "approved_partner_transactions_submit" on public.partner_transactions for insert to authenticated with check((select private.is_approved()) and submitted_by=(select auth.uid()) and status='pending');
create policy "admin_partner_transactions_update" on public.partner_transactions for update to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "admin_partner_transactions_delete" on public.partner_transactions for delete to authenticated using((select private.is_admin()));
create policy "approved_activity_read" on public.activity_messages for select to authenticated using((select private.is_approved()));
create policy "approved_activity_insert" on public.activity_messages for insert to authenticated with check((select private.is_approved()) and created_by=(select auth.uid()));
create policy "admin_activity_delete" on public.activity_messages for delete to authenticated using((select private.is_admin()));
grant select,insert,update,delete on public.partner_transactions to authenticated;
grant select,insert,delete on public.activity_messages to authenticated;
revoke all on public.partner_transactions,public.activity_messages from anon;
create trigger audit_partner_transactions after insert or update or delete on public.partner_transactions for each row execute function private.write_audit_event();
